# Basic
<<<<<<< HEAD
title: Vno Jekyll
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
=======
title: æŽ æ­£
subtitle: ä¸‰äººè¡Œï¼Œå¿…æœ‰æˆ‘å¸ˆ
welcome_message: æ¬¢è¿Žè§‚çœ‹æˆ‘çš„åšå®¢ï¼Œå¦‚æžœæœ‰å…´è¶£ï¼Œè¯·è”ç³»æˆ‘ã€‚è°¢è°¢ï¼
description: Hi, æˆ‘æ˜¯Lambert, çŽ°å±…ä¸Šæµ·ï¼Œå…³æ³¨é¢†åŸŸPython, Docker, Big Data, Cloud Computingã€‚
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Lambert
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: DevOps / è¿ç»´å¼€å‘
url: "http://www.lzzzz.top"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    #weibo: 5366874726
    github: Leejung168
    # twitter: 
    mail: lz8888888888@gmail.com

# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ðŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºŽæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


>>>>>>> aa5777dd3fb36d2459a757ef94d4e1c7e67b5ff8
